### ISSUE TITLE
Delay

### ISSUE THREAD

**Issue by DemonAk** [Tackyou/Gleam.io-Autosolve#10]
It can be a delay after the download page for 5 seconds?, and then perform actions.
In version 1.6 it was possible to put

```
window.open = wo;
                }
            });
            setChance();
        }, 5000);
    }
}
```

in Version 1.7.1 does not work = \

**Comment by Tackyou** [comment]
Why would you want to delay it?

**Comment by DemonAk** [comment]
in order to have time to select a proxy, because I wrote Sorry, you're creating too many entries; try again later.
or maybe to make autosolve at the touch of a button on your keyboard

**Comment by DemonAk** [comment]
I mean a delay before starting the action, ie, the site loaded, it took 5 seconds and then perform actions. 1.8.1 Now when the site is loaded first action is performed without delay = \
