### ISSUE TITLE
Put all the checkboxes instead of the queue

### ISSUE THREAD

**Issue by Wrascon** [Tackyou/Gleam.io-Autosolve#12]
Why did you decide to do queued press ticks instead of fast clicking all at once? Even if Giveaway asked to do several actions to open the other, simply check to see if a new tick appeared to them again and press.

**Comment by Tackyou** [comment]
This has been added recently because you get banned from gleam.io if you do it too fast.

**Comment by Wrascon** [comment]
Ок, I understood
