### ISSUE TITLE
Script don't working

### ISSUE THREAD

**Issue by Dicur3x** [Tackyou/Gleam.io-Autosolve#4]
Script don't working. Just error in match pages. After i edit it (wrote https://gleam.io/*) still don't working. Tested on https://gleam.io/17FZh/hero-defense-haunted-islands-giveaway. Nothing appears and tasks still opens. Mozilla Firefox 45.0.1.

**Comment by Revadike** [comment]
Script does working!!

**Comment by undeference** [comment]
Greasemonkey 3.7 on Firefox Nightly 48.0a1 (2016-03-27) says:

> **Download Error**
> 
> Could not parse scripts:
> Ignoring @match pattern *gleam.io/* because:
> Error: @match: Could not parse the pattern.

Should be fixed by https://github.com/Tackyou/Gleam.io-Autosolve/pull/7

**Comment by Dicur3x** [comment]
Script does working!! - script don't working.
Could not parse scripts:
Ignoring @match pattern _gleam.io/_ because:
Error: @match: Could not parse the pattern.
Yes, this error was, but i changed address and error disappeared, but tasks don't complete automatically.

**Comment by jonniex7** [comment]
now its ok database its loading

**Comment by Tackyou** [comment]
Should be fixed now with Version 1.7
Please update and let me know if everything is fine

**Comment by undeference** [comment]
Works

**Comment by ghost** [comment]
Thank you, Tackyou! It works great now.
