### ISSUE TITLE
autosolve on some twitter without twitter account

### ISSUE THREAD

**Issue by DemonAk** [Tackyou/Gleam.io-Autosolve#5]
I do not have an account twitter
Some giveaway like https://gleam.io/wYgs1/surfeasy-and-opera-giveaway- or other with game giveaway can be done action if you click on tweet button or follow
screen http://i.imgur.com/Ngc7g7d.jpg
Is it possible to make autoclicker on any giveaways?

**Comment by DemonAk** [comment]
or on this giveaway https://gleam.io/AkxLO/free-10000x-deadbreed-special-content-key

**Comment by DemonAk** [comment]
retweet actions https://gleam.io/pekRd/50000x-copies-of-woodle-tree-adventures
http://i.imgur.com/eQ751hB.jpg

**Comment by Tackyou** [comment]
Why don't you connect your twitter account with gleam.io to have it tweet automatically? Without an account you can't solve these steps. They use twitter callback api

**Comment by DemonAk** [comment]
i have twitter on main account, i cant connect on tweet with second account and i can solve twitter steps if click: tweet, follow or retweet (see screenshot, red border), but not all giveaways. Just try to connect gleam with second account without twitter and you can see what i mean

**Comment by DemonAk** [comment]
It looks like a version 1.8 autosolve twitter works fine, thanks
