### ISSUE TITLE
Steam groups

### ISSUE THREAD

**Issue by R1chKa** [Tackyou/Gleam.io-Autosolve#6]
Can't join any steam groups, just cycling every time, when other tasks done (one of them i'm done myself).
![image](https://cloud.githubusercontent.com/assets/11411816/14064983/b75000a2-f41f-11e5-8e8f-419d2c48bfed.png)
UPD. Steam profile is not private:
![image](https://cloud.githubusercontent.com/assets/11411816/14065530/90265bc2-f436-11e5-89c0-447cd2b7f30b.png)

**Comment by Revadike** [comment]
Workaround: hover over the steam group name and then click the link. If you join the group then, it works fine.

**Comment by resrep** [comment]
can you please make it so if the join group task fails once, it doesn't try again?

**Comment by jonniex7** [comment]
royalgamer your script of database http://revolt.loginto.me/index.php?/page/GleamDB doesnt load to me

**Comment by Tackyou** [comment]
This bug is fixed with version 1.7

**Comment by Wrascon** [comment]
I think even log in to Steam, for some reason, your program is not possible to join a group in which has not been before
