### ISSUE TITLE
Install prompt does not show up

### ISSUE THREAD

**Issue by t0stiman** [Tackyou/Gleam.io-Autosolve#8]
> After you installed it, click this link and you should get an install prompt:
> 
> https://github.com/Tackyou/Gleam.io-Autosolve/raw/master/gleamio.user.js

I click the url and FireFox shows me the javascript file, but i get no install prompt.

**Comment by t0stiman** [comment]
I also tried manually adding the script to greasenonkey, and nothing happens on gleam.io .

**Comment by Tackyou** [comment]
There was a bug with the script in Firefox. Please update it should work now.
